spring:
  application:
    name: Haushalter
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

---

spring:
  profiles: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: mysqldev

  datasource:
    url: jdbc:mysql://localhost:3306/haushalter?createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect