spring:
  application:
    name: Haushalter

---

spring:
  profiles: mysqldev

  datasource:
    url: jdbc:mysql://localhost:3306/haushalter?createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect